server:
  port: 9000
  servlet:
    context-path: /api
spring:
  application:
    name: starchat-java
  datasource:
    url: jdbc:mysql://localhost:3306/starchat
    username: jack
    password: 123456
mybatis-plus:
  global-config:
    banner: false
